# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1456f1705f0ab1f3feca56386115cec519e57d4890ba889e4ac653058302e6b67913c606338685ed92fcdef7698084ad5d8e53035e4278aff9c3d351a91b5169

test:
  secret_key_base: 58156f8dbc35c25ff0f793cb1af221987051b72b788e44d66f1e9c711ab9eb587a915d895e9aa4efd6ef7f9e943a0e89fd2075bad48e70aff371908347e0f403

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
